import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Layout from '@/components/Layout'
import profilePic from "../../public/images/profile/developer-pic-1.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightbulb from "../../public/images/svgs/miscellaneous_icons_1.svg"

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>Sorel Mizzi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main className='flex items-center  text-dark w-full min-h-screen'>
      <Layout className='pt-0'>
        <div className="flex item-center justify-between w-full">
          <div className='w-1/2'>
            <Image src={profilePic} alt='Nuamanali' className='w-full h-auto'/>
            </div>
            <div className="flex justify-center items-center h-88 bg-gray-100 p-4">
      <div className="w-1/2 flex flex-col items-center">
        <AnimatedText text="PROFESSIONAL POKER PLAYER." className="text-6xl text-center"/>
        <p className="my-4 text-xl font-semibold">
          Sorel Mizzi
        </p>
        <div className="flex flex-col md:flex-row items-center justify-between gap-4 mt-2 w-full">
          <div className="bg-white p-4 rounded-lg shadow-lg text-center">
            <h2 className="text-lg font-semibold mb-4 text-gray-700">Success Story</h2>
            <p className="mb-4">
              More than just a poker face, see how Sorel Mizzi got his career started, and what it’s taken to get to where he is today.
            </p>
            <Link href="/about" className="inline-block text-white bg-red-500 hover:bg-red-700 font-medium py-2 px-4 rounded-full transition-colors" target="_blank">
                My Story
            </Link>
          </div>
          <div className="bg-white p-6  rounded-lg shadow-lg text-center">
            <h2 className="text-lg font-semibold mb-4 text-red-600">Accomplishments</h2>
            <p className="mb-4">
              Sorel Mizzi has celebrated an accomplished career, and continues to rack up wins.
            </p>
            <Link href="/accomplish" className="text-indigo-600 hover:text-indigo-800 font-semibold">
                Read More
            </Link>
          </div>
        </div>
      </div>
    </div>
       </div>
      </Layout>
      <HireMe/>
      <div className='absolute right-8 bottom-8 inline-block w-24'>
        <Image src={lightbulb} alt='Nuamanali' className='w-full h-auto'/>
      </div>
     </main>
    </>
  )
}
